### ISSUE TITLE
Add git pull to the script

### ISSUE THREAD

**Issue by Gh05d** [faberto/nimiqscripts#1]
For a little improvement, you could change:
```
cd core
npm install
npm run build
cd clients/nodejs
npm install
cd ../../
npm run prepare
```
to
```
cd core
git checkout master
git pull
npm install
npm run build
cd clients/nodejs
npm install
cd ../../
npm run prepare
```

**Comment by faberto** [comment]
As this is an installation script the pull and checkout are not useful here as it gets cloned just seconds before. This would be a nice option for an update script.
